server:
  port: 9000

spring:
  application:
    name: gword-cli
  shell:
    interactive:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.138.44.137:13301/gw-dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: msQl8134!#3

gword:
  # 本地单词储存目录
  localWordDir: /Users/lingui/project/linguiProject/JavaProject/gword/gword/localData/word
